global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mondays-app'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: local
          region: us-east-1

  - job_name: 'mondays-project'
    scrape_interval: 5s
    static_configs:
      - targets: ['monday-go:8080']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8081']